<?php
// ─────────────────────────────────────────────────────────────────────────────
// NEURU — NetOps Copilot KNOWLEDGE BASE.
// Single source of truth for "how the portal works / where things are / how to do
// X". nm_copilot.php ships this to the netops-copilot n8n flow on every chat so the
// LLM answers as a NEURU portal EXPERT (not just a network analyst). Keep the menu
// map in sync with header.php $_nm_groups + the top nav-links, and the page blurbs
// with nm_perm_catalog() in nm_access.php.
//
//   nm_copilot_kb($conn, $context, $username) → big markdown string (the system KB)
// ─────────────────────────────────────────────────────────────────────────────

if (!function_exists('nm_copilot_kb')) {

// One-line "what it does + how to use it" per gated page, keyed by perm key.
function nm_copilot_pagehelp(): array {
    return [
        'net_mon'         => 'Live operations Dashboard — counters, per-node traffic & health, AI Insights strip. Auto-refreshes every 5s (no reload).',
        'incidents'       => 'Incident Command — correlated incidents (signals grouped into one root incident). Acknowledge / resolve / ignore (mute) here. Click an incident for signals + root cause.',
        'net_mon_map'     => 'Network Map — topological node/link diagram with live status. Click a node to troubleshoot.',
        'geomap'          => 'Geo Wall — read-only NOC video-wall: nodes on a world map + animated traffic comets. Opens in a new tab; has fullscreen. Node lat/long is set in Configuration → Nodes.',
        'command'         => 'Command Center — the interactive in-portal NOC. Full-bleed map + draggable HUD glass widgets (layout saved per-user). Add/remove widgets from the Widgets menu; click a node for the troubleshoot dock; fullscreen button. This is also where custom Widget-SDK widgets appear.',
        'federation'      => 'Federation (federation.php) — multi-site cluster. Any NEURU install can be standalone | master | slave (role is config in Setup). Slaves push a compact site rollup (node up/down, incidents) to the master every minute via cron_cluster.php (buffers offline in nm_cluster_outbox, flushes on reconnect); the master shows a federated Overview + a 3D-style **Geo Wall** (Leaflet map with every site as a health-glowing marker + a federated incident feed across all sites, fullscreen), both filtered by a role→site Visibility policy. Register slaves in the Sites tab (per-site token + lat/lon). Cluster Immunity (F3): block a threat once at the master (Immunity tab) → it fans out to EVERY site via a pull command queue (slaves fetch pending commands in their push response, apply through their OWN nm_immunity engine on Pi-holes+firewalls, ack back; at-least-once + idempotent, works through NAT). Federated **Incident desk** (federation.php Incidents tab) + cross-site correlation (same issue at ≥2 sites flagged), and federated **notifications**: the master mirrors site-offline + site-critical events as REAL incidents (root_source=cluster) so the EXISTING Notification Center pipeline (nm_notify_process) alerts them and they appear in the incident desk. **Cluster Time-Travel** (Time Travel tab): a slider replays every site’s state at any past minute over nm_cluster_rollups. In Site Configuration menu. Reuses HTTP+token (no WebSockets), MySQL (no pgvector/SQLite), the geomap tile engine. Engine nm_cluster.php, ingest cluster_ingest.php, cron cron_cluster.php.',
        'live_mon'        => 'Live Monitor — real-time per-node/per-interface stream.',
        'net_mon_stats'   => 'Statistics — historical CPU/memory/traffic charts per node, with the learned baseline (mean ±2σ) overlay where available.',
        'netflow'         => 'NetFlow Analyzer — who/what is using bandwidth (top talkers, apps, protocols, destinations). Flow Explorer filters by host; deep-linkable with ?host=IP. Per-app bandwidth alerts.',
        'l2switch'        => 'Unmanaged Switches — monitors TP-Link Easy Smart switches (no SNMP) by scraping the web UI: per-port pps + link-flap / bad-packet alerts. Add switches in Configuration → Switches tab.',
        'shadowit'        => 'Shadow IT — devices seen on the network that are not in inventory. Scrollable table.',
        'health'          => 'Predictive Health — proactive failure forecasting from optical-SFP DOM trends and ethernet error-rate trends ("fails in ~N days"). The place to confirm a marginal cable/SFP.',
        'gpu'             => 'AI / GPU Monitor — agentless GPU telemetry for AI inference servers (Ollama / LM Studio). Reads nvidia-smi / rocm-smi / Windows GPU counters over SSH (no SNMP OID exists for GPUs) and shows per-GPU utilization, VRAM, temperature, power, fan, clocks + the processes/Ollama model holding VRAM. Add an "AI server" (pick a monitored node for SSH, optional Ollama URL). For matched nodes a GPU panel also appears on the Dashboard & Statistics; there is a gpu.metrics widget data source and a GPU tile on Network Sonar.',
        'timetravel'      => 'Time-Travel — a slider that replays the whole NOC state (nodes, links, NetFlow, incidents, syslog) at any past minute.',
        'chaos'           => 'Chaos Test — "what-if" blast-radius: fail a node and see the cascade with redundancy + business-service impact; ranks single points of failure (SPOF).',
        'heal'            => 'Self-Healing — autonomous playbook orchestrator (detect → propose/act → time-boxed auto-revert). Safety-first: everything is OFF by default; you opt in per playbook. Every proposal FREEZES its firewall-log proof at detection time (evidence snapshot in nm_heal_events), so opening it later always shows the real evidence that triggered it — plus a live "still active?" recurrence check — instead of an aged-out re-query that used to read "thin evidence".',
        'sonify'          => 'Network Sonar — the see-and-hear scope. Pick a target, watch a radar of every node, live traffic vs your thresholds, plain-English "what broke & why" diagnostics, and a "Who is using the bandwidth" NetFlow panel. Every KPI tile is clickable for a drill-down. Audio is muted until you press Start. Thresholds are edited on the page.',
        'wear'            => 'Wear & Stress — cumulative stress scoring per device (how hard it has been worked).',
        'nettools_ping'   => 'Live Ping — interactive, ad-hoc ICMP with a live chart (SSE). Different from Smokeping, which is scheduled history.',
        'nettools_trace'  => 'Traceroute Map — traceroute with per-hop GeoIP + ASN drawn on a world map.',
        'nettools_netstat'=> 'Netstat — socket/connection graph for the NOC host.',
        'nettools_lookup' => 'NS Lookup — forward/reverse DNS lookups (shell-free).',
        'nettools_portscan'=> 'Port Scanner — on-demand TCP port scan of any monitored node or any IP/hostname, with a live WebGL sonar (open ports burst green). Pure-PHP connect scan (no nmap). Public targets require explicit confirm.',
        'log_mon'         =>'Logs — per-device log viewer. NEURU\'s own syslog server is the default source (Graylog optional). Has an "AI Analyze" button for root-cause analysis.',
        'archaeology'     => 'AI Archaeologist — mines historical logs/events for buried patterns and past root causes.',
        'ai_insights'     => 'AI Insights — AI/automation findings as cards (RCA, anomalies, remediation). Blast-radius grouping collapses a storm into one master. "Suggest fix" → remediation card → "Approve & Apply".',
        'copilot'         => 'NetOps Copilot — this assistant. The slide-out chat (wand icon, bottom-right of every page).',
        'containers'      => 'Containers — Docker/Portainer console + AI incident desk. Lists containers, filterable by host; click a container for detail/stats.',
        'smokeping'       => 'Smokeping — latency/packet-loss history. NEURU reads Smokeping\'s RRDs NATIVELY over direct SSH to the Docker host (no n8n) and stores samples in its OWN DB, rendering per-node charts; add/remove targets + sync NEURU nodes from the page. Requires an SSH credential for the Smokeping host (Config → SSH Credentials).',
        'config_mgr'      => 'Config Manager (NCM) — fetches device configs over SSH (n8n), versions them, shows diffs, and alerts on config drift.',
        'router_commander'=> 'Adv. Solution Commander — AI-over-SSH troubleshooting for routers (Python CLI) and linux (n8n bash). Has a destructive-command guard and an Explain/dry-run mode.',
        'wireguard'       => 'WireGuard Orchestrator — create WireGuard servers/peers across vendors (MikroTik / Docker / linux), auto-assign IPs from IPAM, render configs, show QR codes, monitor peers. In the Device Tools menu.',
        'mtfw'            => 'MikroTik Device Manager — a visual, object-based firewall editor for RouterOS. Reads /ip firewall filter + NAT + address-lists over SSH and shows the rules per chain IN ORDER with action badges + live hit-count heatmap (dead/never-hit rules flagged). Build/edit rules as objects (dropdowns + address-list objects), PREVIEW the exact `/ip firewall …` command (dry-run), then inject with SAFE-APPLY: a RouterOS scheduler auto-reverts the change in N minutes unless you click "Keep" — so a bad rule can\'t lock you out (commit-confirm). Also: a 3D **Packet Tracer** (mtfw_trace.php — a Cisco-Packet-Tracer-style WebGL animation where a crafted packet flies through the firewall\'s rule "gates", sailing past rules it doesn\'t match and stopping at the exact gate that ACCEPTS/DROPS it, with a synced rule-by-rule log; resolves real address-list membership; read-only), templates (secure-router / port-forward / block-IP), and firewall drift detection. Strict per-field validation (command-injection safe). Admin-only by default. In the Device Tools menu. Perm: mtfw.',
        'pihole'          => 'Pi-hole — Pi-hole v6 monitoring: dashboard + live query log via a server-side API proxy (encrypted password).',
        'adguard'         => 'AdGuard Home — network-wide DNS ad-blocking monitor, mirrors Pi-hole: dashboard (queries/blocked/top domains+clients/chart) + live query log via a server-side proxy to the AdGuard /control REST API (HTTP Basic, username+password stored encrypted). Configured in Config → Integrations → AdGuard Home. Also a Collective Immunity target — blocking a threat domain fans out to every AdGuard as a ||domain^ user-rule, just like Pi-hole. Perm: adguard.',
        'weather'         => 'Weather Routing — overlays severe-weather risk on sites/links.',
        'immunity'        => 'Collective Immunity (immunity.php, Healing menu) — block a threat ONCE and fan it out to ALL Pi-holes (DNS deny) + firewalls (SSH). Auto-detects port-scans (syslog) / malicious DNS (Pi-hole logs). Select many threats and "Vaccinate the selected" → they distribute with a LIVE per-threat progress bar (streams "3/12 — <indicator>… · N applied") so it never looks frozen; the portal stays responsive during the fan-out. Revoke pulls a block back everywhere. Perm: immunity.',
        'deception'       => 'Deception Grid — instead of just banning an attacker IP, DIVERT it into a decoy honeypot by reconfiguring the border router\'s firewall: a dst-nat sends the attacker to the honeypot (placed FIRST so it wins over other NAT) PLUS a first-position ALLOW filter rule WITH logging (so the honeypot actually receives the traffic and every hit is captured for "Watch"), time-boxed + auto-reverting. VENDOR-UNIVERSAL renderers: MikroTik (full, verified live) and Cisco ASA today; TP-Link/TrendNet/others pluggable (unsupported vendors fail honestly). Watch fills from the router\'s firewall log (ingested on-watch + each cron sweep). Then the AI analyst judges it and you "Promote" to a fleet-wide Collective Immunity block. Autonomous mode (auto-divert Immunity port-scans → auto-analyze → auto-promote). OFF by default, one-source scoping, never-divert allowlist (incl. NEURU\'s own IP), border-path aware, fully audited. In the Healing menu. Full guide: docs/DECEPTION_GRID.md.',
        'ipam'            => 'IP Address Management — subnets, allocations, conflicts, utilization. A single-source-of-truth built on top of the existing node/interface inventory (not a parallel database). In the Site Configuration menu.',
        'reports'         => 'SLA & Reports — uptime/SLA per node and exportable reports.',
        'net_mon_config'  => 'Configuration — the main settings hub (tabbed): Nodes, Global Settings (poll intervals, retention, SNMP, Ping Down Sensitivity, Display Timezone), Discovery, Switches, Smokeping, NetFlow, Syslog, Pi-hole, Integrations & AI (n8n webhooks, inbound token, SSH credentials), and more.',
        'user_admin'      => 'Access Control — users, roles, and per-user permission overrides (layered RBAC, deny-wins). Lockout-proof and audited.',
        'about'          => 'About — cinematic end-credits page: developer (Hector Miranda, System Engineer), portal version, and a scrolling roll of every open-source project NEURU uses. In Site Configuration. Visible to all roles.',
        'audit_log'       => 'Audit Log — every sensitive action, who did it and when.',
        // ── landing + the two "command centers" (do NOT confuse them) ─────────
        'home'            => 'Command Deck — the post-login home/launchpad (rocket icon, top-left). Live NOC vitals (nodes up/down/degraded, open incidents, avg uptime, DBs OK, active AI sessions) + a searchable, permission-filtered grid of EVERY module + your pinned/recent pages. Press "/" to search, Enter opens the first match.',
        'autopilotv2'     => 'NEURU Commander (autopilotv2.php) — NEURU\'s flagship autonomous NOC cockpit (Command Centers menu). A WebGL "neural core" + a signal bus that turns every alert (nodes down, incidents, threats, heal, deception, predictive) into an investigation via a metered LiteLLM brain; it PROPOSES/auto-runs vetted fixes (portal executes, never the LLM) with Telegram approvals. Talk to it by TEXT or by VOICE (VAPI) — the same brain. Regenerative MEMORY (learns facts/corrections, recalls before answering). FIVE full-screen WebGL overlays it can open/close/focus BY VOICE (mutually exclusive): Surgical X-Ray (live 3D node anatomy — CPU/mem/GPU/net/disk/thermals), Topology Map (all nodes interconnected), Live Traffic (laser-per-interface), Containers (every Docker container per node as glowing towers, with volumes/sizes/partition/net Q&A), and Net Tools (Port Scanner radar / Live Ping / Traceroute geo-map / Netstat / NS Lookup embedded). A deterministic 5-stage Troubleshooting engine (fingerprint→symptom→test-battery→neighbor-correlate→verdict) that decides "hay o no problema". Optional VOICE NARRATION of autonomous investigations (opt-in, never interrupts a live conversation). Say things like "muéstrame el x-ray de core-router", "los contenedores del nodo X", "escanea los puertos de X", "activa el modo autónomo".',
        'gaming'          => 'Gaming Deck (gaming.php, Gaming menu — formerly "Game Mode") — a futuristic WebGL gamer command center that reuses NEURU\'s agentless Windows + GPU (SSH) telemetry, reframed for gamers. A "rig" = a monitored Windows host. Features: live GAME DETECTION (auto-detects Valorant/CS2/Fortnite/CoD/Apex/LoL… from running processes); a GPU/Thermal reactor (util/VRAM/temp + animated fan + THERMAL-THROTTLING alert); REAL FPS + 1% / 0.1% lows via PresentMon (1-click deploy over SSH; needs an admin SSH user) with a per-session summary (duration, max temp, peak VRAM); a Game Ping Radar that pings the running game\'s official server regions FROM the gamer\'s PC (latency + jitter + packet-loss + which server); a 1-Click reversible Game Booster (High-Performance power plan + stops junk services); a Bandwidth-Hog detector; a Game Server Status board (12 famous services — Riot/Steam/Epic/Blizzard/etc. — plus your OWN server with LIVE player counts via Minecraft Server-List-Ping and Source/A2S queries); and an OBS/Streamlabs LIVE OVERLAY generator (creates a tokenized public overlay.php URL you drop into OBS as a Browser Source → a transparent futuristic HUD of ping/FPS/GPU/CPU on your stream, with themes Synthwave/Matrix/Neon/Obsidian and step-by-step setup instructions); plus a 3D COMMAND DECK (immersive fullscreen cockpit — reactor + orbiting metric satellites + 3D spinning fans + floating rig specs, drag to orbit / scroll to zoom). **God-tier layer (customer-acquisition):** ADAPTIVE HUD SKINS (the whole UI auto-themes to the detected game — Cyberpunk, Valorant, Elden Ring, CoD… — "✨ Auto skin"); a NEURU COPILOT (a reactive battle-buddy card + a panel on the 3D deck that fires event-driven micro-alerts only when something crosses to stress — thermal-throttle, VRAM-maxed, CPU-bound, network jitter, frame-stutter — with 1-click safe actions to the Fan Profiler / Connection Doctor / Game Mode boost, plus optional BROWSER VOICE that speaks the alerts); a PLAYER DNA panel (a gamer archetype — Thermal Zen / Precision Sniper / Speedrunner Optimized… — computed from your real session history, with 5 traits + Level/Rank) and ACHIEVEMENTS (a technical battle-pass: Sub-Zero, Frame Lord, Rock Solid, Marathoner…, shown on BOTH the page and the 3D deck); a GAMEMODE ON toggle + a FAN-PROFILE SWITCHER right in the 3D deck. Perm: gaming.',
        'fan_profiler'    => 'NEURU Fan Profiler (fan_profiler.php, Gaming menu) — a fully-WebGL cockpit to view, tune and switch the gamer\'s FanControl (github.com/Rem0o/FanControl) fan-curve config files over the same agentless Windows-SSH. Reads the FanControl config JSONs (default C:\\Program Files (x86)\\FanControl\\Configurations, path overridable), auto-opens the newest, and shows every CURVE as an editable graph (DRAG the dots to reshape) — including Mix curves (Max/Min/Average/Sum of member curves) — plus a Fans panel where each fan follows a curve (or Manual + slider). NO auto-save: edits stage in an "Unsaved changes · Save / Discard" bar; then "Apply profile" copies it over configuration.json and relaunches FanControl (~2s). Live temps + REAL fan RPMs come from LibreHardwareMonitor (matched per fan by hardware id, updates every ~2s). A 3D RIG scene shows live component heat (CPU/GPU/VRM/RAM/NVMe colored by real temp), spinning fans at their live RPM, airflow, and critical-zone glow — fullscreen + click any component for its temp. Advises how to run cooler (acts on the full LHM sensor tree: VRAM-junction/VRM/NVMe/RAM). HARD RULE: never nag to change an AIO pump (runs 95-100% flat-out per cooler spec) — only soft suggestions for manual fans, always respecting the user\'s choice. Perm: gaming.',
        'game_hub'        => 'Gamers Hub (game_hub.php, Gaming menu — the ONLY nav item; every other gaming tool is reached from here) — the futuristic full-WebGL landing/launcher for the whole Gaming section. A central rotating NEURU core with every gaming tool as a floating holographic portal-card in a ring, each wired to the core by an energy stream with a travelling pulse. Cards are drawn to canvas textures (real 3D WebGL cards). Hover pops a card out + brightens its neon border & stream; clicking warp-DIVES into that page (the card flies into the camera, others streak away, white flash, then navigate). Cards are RBAC-gated: shows only the tools the user can open — Gaming Deck, Game Lab, Parallel Reality, Synaptic Map, Connection Doctor, Fan Profiler (perm gaming) and PC Doctor (perm pc_doctor). Perm: gaming.',
        'benchmark'       => 'PC Benchmark (benchmark.php, reached from the Gamers Hub) — answers "is this PC good for gaming?" with a real, reproducible NEURU Score (0–10,000) + Tier (S/A/B/C/D). The actual test runs LOCALLY on the gamer\'s Windows rig via one PowerShell-over-SSH call (nm_benchmark.php): a timed CPU compute loop, a 64MB sequential storage I/O test, and a full hardware probe (CPU cores/threads/clock, RAM GB+MHz+sticks, GPU name + true VRAM via registry qwMemorySize, disk media/bus, resolution/refresh). PHP then composes a gaming-weighted score — GPU 55% · CPU 22% · RAM 12% · Storage 11% — reusing the SHARED universal GPU classifier (nm_gf_gpu_class) so it agrees with Game Lab\'s FPS Guarantee. Full-WebGL "reactor" (central core + 4 orbiting component nodes with gauge rings sized by sub-score, animated score count-up, tier colour), a live staged run console, an estimated in-game FPS box, per-component cards, and detailed findings each with plain-English "what it means" (novice) + "the data" (expert) + deep-links to the right fix tool (Game Lab / Fan Profiler). Detects CPU↔GPU bottleneck, low VRAM, single-channel RAM, HDD-as-game-drive. Perm: gaming.',
        'longevity'       => 'Hardware Longevity · Health Passport (longevity.php, reached from the Gamers Hub) — a CUMULATIVE wear & lifespan view of the gamer\'s Windows rig. Unlike PC Benchmark (an instant capability score), this ACCUMULATES real agentless telemetry over time (a "Scan now" button + the cron_wearlife.php */10 cron fold snapshots into nm_hw_wear) and projects what\'s aging. Four subsystems, each honestly labelled: (1) SSD/NVMe NAND endurance — REAL SMART Wear% via Get-StorageReliabilityCounter → a real lifespan projection (months/years left at the current write rate); (2) Thermal Stress — accumulated hours GPU/CPU spent in the >83°C zone (exposure estimate, not a fake %); (3) Power Delivery/VRM — accumulated hours at sustained 95%+ load; (4) Fan Bearing Wear — high-RPM hours + max RPM. Composite Longevity Grade (S/A/B/C/D) weighting SSD wear most, plus a Maintenance Forecast (e.g. "thermal-paste refresh in ~7 months", "SSD nearing rated writes"). Full-WebGL: central health core + 4 orbiting subsystem gauge-nodes, fullscreen, mouse-orbit. Reuses nm_gaming_sensors (LHM/OHM over SSH) + nm_gf_gpu_class. Perm: gaming.',
        'game_lab'        => 'Game Lab (game_lab.php, Gaming menu) — a suite of one-click gamer OPTIMIZERS/FIXERS that run agentless PowerShell on the gamer\'s Windows rig over the same SSH stack as the rest of Gaming (nm_gamefix + nm_winhost). Pick a rig, run a tool → it renders a "Tactical Console" (animated step-log + a WebGL holographic Stability-Score orb + 🟢/🟡/🔴 badges + plain findings + reversible 1-click fixes). The six tools: (1) NETWORK AUTO-HEAL — measures ping/jitter/loss + adapter + fastest gaming DNS, then a Pre-Flight Clean (flush DNS + Winsock reset + IP renew + ARP purge) and Set-fastest-DNS (the "cure" half of Connection Doctor); (2) AUTO-REPAIR — the "my game won\'t open" fixes: repair Gaming Services/Xbox auth, purge Steam/Epic/Battle.net/EA launcher caches, reset firewall rules, SFC+DISM integrity repair; (3) CRASH SHIELD — pre-flight risk: overlay-collision radar (RTSS/Discord/GeForce/Steam/MSI), anti-cheat presence, recent crash events, kernel-handle leaks, with a Crash-risk % and a 1-click suspend of a conflicting overlay; (4) DRIVER & FIRMWARE — GPU driver, NVMe firmware, BIOS, Device-Manager conflicts, and DPC latency (advisory Stability Score Matrix); (5) STORAGE OPTIMIZER — SSD-SAFE: analyze fragmentation, ReTrim SSDs (never NAND-wear defrag), defrag HDDs only, purge stale shader caches; (6) FPS GUARANTEE — a per-rig FPS contract (avg + 1% low from GPU tier × resolution) with Competitive / Golden Balance / Ultra graphics presets. Every fix is audited; WebGL neural background. Perm: gaming.',
        'synaptic'        => 'Synaptic Map (synaptic.php, Gaming menu) — extends Player DNA into a live 3D WebGL NEURAL MAP of the player↔machine symbiosis. A central "sync-core" with 5 radial synaptic pathways built from the rig\'s real session history (nm_gaming_dna traits): FPS Resilience, Latency Resistance, Thermal Composure, Endurance, Adaptability — each a glowing axon+node whose brightness/size = strength and that FRACTURES red when weak (<45). A central SYNAPTIC SYNC INDEX (0-100) = the harmony between the player\'s reflexes and the system\'s health. Issues a shareable CYBORG PROFILE card (Thermal Sensitive / Low-Latency Dependent / Adaptive Cyborg / Frame Hunter / Balanced Operator) computed from the weakest/dominant pathway. INTERACTIVE: every synapse is labelled in-scene (name + score), node SIZE = strength, a gauge RING shows the exact 0-100 score, and pulse SPEED = consistency; hover shows a tooltip and clicking a node (or a pathway row) opens an analytics panel with plain-English "What it means" (novice) + "The data behind it" (expert, grounded in real numbers like best FPS / 1%-low ratio / avg peak temp / hours / games) + a "level up" action that deep-links to the right tool (Game Lab / Connection Doctor / Fan Profiler). Has a FULLSCREEN button (map + analytics overlay go full-viewport). Perm: gaming.',
        'reality'         => 'Parallel Reality Engine (reality.php, Gaming menu) — the flagship gamer experience: a WebGL "multiverse" of the rig. Pick a rig → preview 4 timelines on a Reality Slider: α (live now, amber), β (Max-Performance/Competitive, neon-blue), γ (Silent/Low-Power, cyan), δ (custom, violet) — each shows projected FPS / GPU temp / ping / fan-RPM vs your current reality. α is LIVE (gaming vitals); β/γ are modeled from the same real telemetry + the FPS/thermal engines. Press "COLAPSA ESTA REALIDAD" and NEURU applies the REAL Game Lab optimizers that make that future true (β = network Pre-Flight Clean + Competitive FPS preset; γ = quiet profile) — reversible, with a sci-fi collapse animation. Four rotating reality-cores in 3D themed to the selected timeline. Perm: gaming.',
        'connection_doctor'=> 'Connection Doctor (net_doctor.php, Gaming menu) — a gamer network-quality diagnostic rendered as a WebGL data-highway YOU → Router → ISP → Internet → Game. Measures ping / jitter / packet-loss / stability both from the gamer\'s PC (over SSH) and from the NOC, gives a plain verdict (is it your WiFi, your ISP, or the game server?), and keeps a monitoring history. Sibling of PC Doctor. Perm: gaming.',
        'pc_doctor'       => 'PC Doctor (pc_troubleshoot.php, Gaming menu) — a fullscreen WebGL virtualization of the gamer\'s ACTUAL PC for hardware troubleshooting. Reads the real hardware inventory over the same agentless Windows-SSH stack (CIM/WMI): CPU, motherboard + BIOS, each RAM DIMM, GPU(s), NVMe & SATA disks, and PCIe cards (network/audio). Renders them as a 3D motherboard you orbit/zoom with the mouse; CLICK any component to open its true brand · model · version, its live temperature, and real links (manufacturer page · full specifications · product photos). Data "currents" flow across the board driven by live CPU/GPU load, and components glow by live temperature. Perm: pc_doctor.',
        'neurutik'        => 'NEURUTIK (Unified Command Center) — one WebGL galaxy that UNIFIES the individual command centers onto the SAME nodes (it does NOT replace them; community-requested). Every registered node is a health-coloured core (blue/router, amber-ring by kind) in a force-directed constellation with live link particle streams. Toggle LAYERS to overlay each metaphor on the same nodes: ⚡ Traffic (particle brightness/speed ∝ nm_port_stats rate), 🧭 Routes (protocol-coloured route conduits from nm_routing_topology), 🗄️ DB (Data Core reactors from nm_dbobs_scene, pulse=load), 🧬 Services (Biosphere cells orbiting their node from nm_bio_scene), 🌌 Hologram (particles coloured by top NetFlow app from nm_holo_enrich). Click any node → a full dossier (status/latency/avail/CPU/RAM/uptime + incidents + AI insights + predictive health + interfaces + NetAIObot + recent logs, via nm_holo_node_detail) and a one-click DEEP-LINK to that node\'s OWN per-kind command center (windows→win_screen, linux→linux_screen, router→router_details, resolved by nm_node_cc). Drag to orbit, scroll to zoom, auto-rotates. In the Command Centers menu (top). Perm: neurutik.',
        'matrix_flow'     => 'NEURUTIK Matrix Flow — an IP-centric 3D flow matrix (WebGL), distinct from the topology Hologram: every NetFlow conversation is a LASER between a source and destination IP. Beam THICKNESS = bandwidth (Mbps), travelling PULSE speed = latency (ms), colour/state = health: teal normal, thick yellow = saturation/bottleneck, red + broken/flickering pulses = packet loss, and a source opening many destinations lights up a red anomaly ring (port-scan / high connection density). Local IPs orbit an inner plane (spheres), external IPs are prisms on the outer perimeter with their COUNTRY FLAG. Click an IP = Laser Focus (isolates its in/out beams) + a dossier (in/out Mbps, latency, loss, peers, its heaviest flows with exact port/proto, deep-link to that node\'s command center or NetFlow). Hover a beam to read the exact port/protocol (e.g. TCP 443). Two refresh modes: normal (6s) and ⚡ Real-Time (2s). Reuses NetFlow (nm_nf_*) + geo flags (nm_geo_badge) + ping latency/loss. In the Command Centers menu. Perm: matrix_flow.',
        'hologram'        => 'Traffic Hologram — a 3D "gemelo digital" (WebGL) where bandwidth is VOLUMETRIC: GPU particle streams flow through the virtual cables between nodes — density = live throughput, color = the application flowing (from NetFlow). Drag to orbit, scroll to zoom, click a node to investigate. Reuses the live topology + rates; read-only. In the Command Centers menu and via a "Hologram" button in Command Center.',
        'biosphere'       => 'Service Biosphere — a LIVING 3D twin (WebGL) where each monitored SERVICE (DNS / HTTP / SQL / SMTP / generic TCP) is an organic CELL. Every visual maps to a REAL protocol vital: the membrane breathes faster + swells as latency rises, paints dark "infection" patches on real 4xx/5xx errors, turns to "sludge" on SQL saturation/slow-query pressure, and freezes to ice on a DB lock/deadlock; hibernating dependents go translucent. Probes are server-side PHP sockets (no new binaries); SQL cells REUSE Data Core (no new creds), DNS cells can link a Pi-hole for cache-hit/blocked ratios. Click a cell → dossier (latency sparkline, kind-specific vitals, heaviest queries for SQL, flags, symbiosis links). Symbiosis edges reuse incident correlation. Manage cells via the 🎛 Manage drawer (Services / Add-Edit / Antibodies / Settings). The cron_biosphere.php poller must run every minute. In the Command Centers menu. Perm: biosphere. **P2 intelligence (built):** (1) DNS DGA audit — Pi-hole-linked DNS cells ship unusual high-entropy resolved domains to the n8n "bio-dns-audit" flow (OpenAI); verdicts become Antibody flags and score ≥ threshold auto-promotes to a fleet-wide Collective Immunity block. (2) SQL Auto-Tune — a distressed SQL cell (slow queries/locks) raises a flag; "🧠 Analyze" reuses the Data Core "db-advisor" flow, and a whitelisted index/maintenance suggestion gets an "⚡ Apply now" button — since you are in the portal, clicking IS the approval: it applies via nm_db_apply_advice immediately and broadcasts a heads-up to your enabled notification channels (no self-approval Telegram round-trip; a two-way Telegram approval exists but is reserved for a future autonomous mode). **P3 synthetic persona (built):** an HTTP cell can define a "journey" (login + goto/click/expect/fill/wait steps) run by a headless browser in the n8n "bio-http-synthetic" flow, measuring Visual Completeness Time; a broken journey raises a ux_break flag and the cell visually SPLITS off a wireframe clone (rendered UX diverging from the healthy structure). Login password is nm_secret-encrypted. Edit via a cell dossier → ✎ Define journey; enable in Settings. Contracts: docs/N8N_BIOSPHERE.md. n8n slugs: bio-dns-audit + bio-http-synthetic (auto-listed in Config→Integrations, paste URL + Enable), db-advisor (reused).',
        'troubleshoot'    => 'Troubleshoot Wizard — a guided, real-time, step-by-step diagnosis of one node (connectivity → resources → interfaces → logs → database) with expert knowledge baked in. In the Monitoring menu.',
        'windows'         => 'Windows Monitor — agentless Windows-over-SSH suite (PowerShell): Event Log feed, a live Troubleshoot tab (what is eating CPU/RAM/network, full sensor tree), and a per-host immersive Command Center screen (win_screen.php).',
        'linux'           => 'Linux Monitor — agentless Linux-over-SSH suite (bash); the mirror of the Windows module. Per-host metrics (node_exporter/Alloy :9100), live diagnostics, and a per-host screen (linux_screen.php).',
        'watchdog'        => 'Service Watchdog (watchdog.php) — one fleet-wide cockpit for EVERY watched service across all Linux + Windows hosts: live state, arm/disarm auto-restart, restart-now, restart counts, and a "Sweep now" that reads states over SSH and auto-restarts armed+stopped services (5-min backoff, audited). The per-host watch tabs in Linux/Windows Monitor still work; this is the aggregate view. Reuses nm_lx_watch/nm_win_watch — no new tables.',
        'routers'         => 'Router Monitor — the fleet view of every router-class device (MikroTik RouterOS / Cisco), the analog of Windows/Linux Monitor. Cards show live reachability, latency, 24h uptime, incidents and the equipment photo; each opens an immersive per-device dossier (router_details.php) with live RouterOS telemetry over SSH + the asset/inventory panel.',
        'sla_live'        => 'SLA Live Center — a per-node LIVE availability cockpit: SVG SLA ring gauges + SRE error-budget bars + an outage↔incident timeline drawer. Complements "SLA & Reports" (which is historical + exportable).',
        'dbmon'           => 'Data Core — agnostic database monitoring (MySQL/MariaDB + PostgreSQL) linked to your nodes. Dual transport: direct (PDO) or SSH-native client (no system installs needed). Health/latency now; roadmap adds Deadlock Radar, CRUD Heatmap, Index Archaeologist, Schema Drift, Replication Monitor. Add DB targets on its config tab.',
        'router_center'   => 'Router Command Center — a fullscreen WebGL command space showing EVERY registered router at once, each as its own live traffic hologram: a pulsing core + interface ports on a ring + real per-interface packet streams (cyan in / amber out, from a RouterOS dual-sample SSH probe). Cores are health-coloured (blue healthy / amber has-incident / red down) so problems pop instantly. Click a router to focus it and read its live per-interface throughput in the side panel, then jump to full Router Details or the Commander. The fleet-wide sibling of Router Details (router_details.php). In the Command Centers menu. Perm: router_center.',
        'remote_console'  => 'Remote Console (remote_console.php) — from the MASTER, drive a remote slave site\'s WHOLE menu as if you were sitting in front of it. Pick a site, pick any module from the rail (mirrors the local nav), and its NATIVE page loads embedded read-only via the short-lived HMAC SSO token (no second login) — the SAME embed the Federated Device view uses, extended to the entire portal. Read-only by design: the fed bypass authorizes GET only, so every dashboard renders + auto-refreshes live while writes (POST) stay blocked. Modules are either viewable-now (allowlisted in nm_fed_auth.php, audited to never echo a secret over GET) or locked with the reason: "action" (mainly performs writes/executes — those go through the Actions drawer, not the embed) or "secret" (can expose credentials over GET, e.g. Config Manager — never embeddable). **Phase 3 remote ACTIONS (BUILT):** admins get an "Actions" button (top bar) opening a drawer that ENQUEUES vetted operations to the chosen site via the cluster command queue (nm_cluster_cmd_enqueue → the slave applies on its next check-in ~1min through nm_cluster_apply_command under its own privilege → acks the result back, shown in a live per-site results feed). v1 actions: Re-poll node, Restart service (Linux systemctl / Windows Restart-Service, resolved from node→host), Block IP/domain (fleet-wide Immunity), Maintenance window (silence alerts N min). The embed stays GET-only read-only; the queue is the ONLY write path and every enqueue is audited. The master\'s OWN site applies instantly. Your BROWSER embeds the remote portal directly (it must reach that site\'s Portal URL; the master server can\'t through NAT). In the Command Centers menu. Perm: federation. Engine nm_cluster.php + nm_fed_auth.php.',
        'wifi'            => 'WiFi Control Center (wifi.php) — monitor AND control WiFi controllers of ANY family over SSH CLI, universal via a DRIVER model (nm_wifi.php). Cisco AireOS / Mobility Express is wired up now (your 3802I in standalone = an embedded AireOS controller); IOS-XE 9800, autonomous IOS, Aruba, UniFi, MikroTik CAPsMAN are declared driver slots. Register any node that is a WiFi controller (it needs an SSH credential); NEURU auto-detects the family via `show sysinfo`. Tabs: Overview (sysinfo + client/AP/WLAN counts + uptime), Clients (live associated list, per-client detail drawer = RSSI/SNR/throughput/capabilities via `show client detail`), Access Points, WLANs/SSIDs, RF (5GHz channel/tx-power). Core actions (admin only, confirm + audited): deauth a client (`config client deauthenticate`), block/unblock a MAC (exclusion list), reboot an AP (`config ap reset`), reboot the controller (`reset system`). Each driver declares a CAPABILITY MATRIX so the cockpit only offers what THAT controller supports. Transport = scripts/nm_wifi_ssh.py (interactive shell: pager off, optional 2nd login, y/N confirmations). A Manage tab has a Raw CLI transcript viewer to tune parsers against a real box. NOTE: "add a client" in WiFi = allow/block a MAC (clients associate themselves; you can deauth/block/allow, not force-join). RBAC: view=perm wifi, all writes=admin. In Device Tools. Autonomous mode (auto-deauth/reboot/channel via NEURU Commander+self-heal) is a planned Phase 2.',
        'license'         => 'Licensing (license.php, Site Configuration, admin) — where you point this NEURU install at your License Portal and manage its license. Shows the live entitlement state (tier, node limit, status, valid token, grace-until, machine fingerprint, last check). Set the portal API URL (ends in /api.php on the test build), paste a license KEY to Activate (binds this machine + gets a signed Ed25519 token verified locally by the embedded public key — the private key never touches this install), Revalidate (heartbeat), or Deactivate (frees the slot). An Enforcement toggle (default OFF = full product, nothing gated; ON = pages with a feature-gate honor the token tier). Engine nm_license.php + nm_feature() gate. A perpetual/offline token (e.g. an owner Enterprise-forever grant, grace far in the future) shows a note not to re-activate. Also has a **Billing & Balance** card (visible to all users) that pulls the customer\'s live account state from the Portal (/v1/billing): plan/tier, and for a SUBSCRIPTION the monthly amount + next-payment date, plus the AI-credit balance remaining and recent ledger. Free tier shows $0 monthly.',
        'routing_center'  => 'Routing Command Center — the live Layer-3 forwarding fabric of the whole estate. Each router is pulled for its routing table (RouterOS via SSH; connected-subnets fallback for any brand), and every route\'s gateway is resolved to the OWNING router → the real topology is rebuilt from the routing tables. WebGL: router cores + protocol-coloured route conduits (connected=teal, static=blue, dynamic=purple, default→Internet=amber), connected subnets orbiting, an Internet cloud for default routes. Features: device selector, protocol filters, per-router route table + route DRIFT/flap + "who transits through me", a longest-prefix PATH SIMULATOR (type a dest IP → animated hop-by-hop path with outcome: delivered/internet/blackhole/LOOP/no-route), a live NetFlow-on-routes overlay (conduit load ∝ real traffic), and routing-LOOP detection. In the Command Centers menu. Perm: routing_center.',
        'dbobs'           => 'DB Observatory — a LIVING 3D holographic twin of the Data Core (WebGL). Every configured database is a REACTOR: the core pulses with running threads, an orbital ring fills with the connection pool (red when saturated), a GALAXY of table tiles spins around it (size = rows, colour = read↔write, from the I/O heatmap), a replication CONDUIT streams particles master→replica (green in-sync / amber behind / red thread-down), and lock waits freeze the core. Every visual is a REAL Data Core signal — reuses nm_dbmon (probe/live/replication/topQueries/heatmap) verbatim, read-mostly. Click a reactor → dossier (vitals, replication, heaviest queries with no-index flags, slow/locks, AI advice with ⚡ Apply now, busiest tables, connections trend). 2D fallback if no WebGL. In the Command Centers menu. Perm: dbobs.',
        'thresholds'      => 'Thresholds & Sensitivity — one page to tune ALL alert thresholds/sensitivity (CPU/memory/disk levels, loss/latency, reboot detection) to cut false positives. In Site Configuration.',
        'widgets'         => 'Widget Studio — the no-code widget builder: pick a curated data source + a look (stat/list/bar/table/alarm/sonify), map fields, live-preview, Save. Built widgets then appear in the Command Center Widgets menu.',
        'widget_market'   => 'Widget Marketplace — install ready-made NEURU or community widgets (Preview/Code before installing). You can delete only widgets YOU created.',
        'widget_sdk'      => 'Widget SDK Guide — reference of all live widget data sources + a copy-able AI prompt so an AI can write a `.neuruwidget` for you to import.',
        'notify_admin'    => 'Notifications & Maintenance — the CENTRAL alert pipeline: channels (n8n, generic webhook, Telegram, email), escalation steps, and maintenance windows that suppress alerts site-wide or per node/source. Every module alerter routes through here.',
    ];
}

// The exact menu placement, mirroring header.php (top nav-links + dropdown groups).
function nm_copilot_menu_map(): array {
    return [
        'Top bar (always visible)' => [
            ['Home (Command Deck)', 'home'],
            ['Dashboard',           'net_mon'],
            ['Incidents',           'incidents'],
        ],
        'Menu ▸ Command Centers' => [
            ['NEURU Commander (flagship)','autopilotv2'],['Command Center','command'],['Map','net_mon_map'],['Geo Wall (new tab)','geomap'],
            ['Traffic Hologram','hologram'],['Router Command Center','router_center'],['Routing Command Center','routing_center'],['Remote Console','remote_console'],['DB Observatory','dbobs'],['Service Biosphere','biosphere'],
        ],
        'Menu ▸ Monitoring' => [
            ['Troubleshoot Wizard','troubleshoot'],['Live','live_mon'],['Stats','net_mon_stats'],
            ['NetFlow','netflow'],['Unmanaged Switches','l2switch'],['Shadow IT','shadowit'],
            ['Predictive Health','health'],['Windows Monitor','windows'],['Linux Monitor','linux'],['Service Watchdog','watchdog'],['Router Monitor','routers'],
            ['Time-Travel','timetravel'],
            ['Chaos Test','chaos'],['Network Sonar','sonify'],['Wear & Stress','wear'],['SLA Live Center','sla_live'],['Logs','log_mon'],
        ],
        'Menu ▸ AI Tools' => [
            ['AI Insights','ai_insights'],['AI / GPU Monitor','gpu'],['AI Archaeologist','archaeology'],
        ],
        'Menu ▸ Ext Monitoring' => [
            ['Containers','containers'],['Data Core (DBs)','dbmon'],['Smokeping','smokeping'],['Pi-hole','pihole'],['AdGuard Home','adguard'],
            ['Weather Routing','weather'],
        ],
        'Menu ▸ Healing' => [
            ['Collective Immunity','immunity'],['Self-Healing','heal'],['Deception Grid','deception'],
        ],
        'Menu ▸ Net Tools' => [
            ['Live Ping','nettools_ping'],['Traceroute Map','nettools_trace'],
            ['Netstat','nettools_netstat'],['NS Lookup','nettools_lookup'],['Port Scanner','nettools_portscan'],
        ],
        // The Gaming nav has ONE entry: Gamers Hub. Every gaming tool below is reached
        // FROM the hub (its portal-cards), and every gaming page has a "Gamers Hub"
        // back-pill. So to open Game Lab / Parallel Reality / etc., tell the user to
        // go Gaming ▸ Gamers Hub and pick the tool's card.
        'Menu ▸ Gaming' => [
            ['Gamers Hub','game_hub'],
            ['Connection Doctor (via Gamers Hub)','connection_doctor'],
            ['Fan Profiler (via Gamers Hub)','fan_profiler'],
            ['Gaming Deck (via Gamers Hub)','gaming'],
            ['Game Lab (via Gamers Hub)','game_lab'],
            ['Parallel Reality (via Gamers Hub)','reality'],
            ['Synaptic Map (via Gamers Hub)','synaptic'],
            ['PC Benchmark (via Gamers Hub)','benchmark'],
            ['Hardware Longevity (via Gamers Hub)','longevity'],
            ['PC Doctor (via Gamers Hub)','pc_doctor'],
        ],
        'Menu ▸ Device Tools' => [
            ['Config Manager','config_mgr'],['Adv. Solution Commander','router_commander'],['WireGuard Orchestrator','wireguard'],['MikroTik Device Manager','mtfw'],['WiFi Control Center','wifi'],
        ],
        'Menu ▸ Site Configuration' => [
            ['IP Address Mgmt','ipam'],['SLA & Reports','reports'],['Config','net_mon_config'],['Thresholds & Sensitivity','thresholds'],
            ['Widget Studio','widgets'],['Widget Marketplace','widget_market'],['Widget SDK Guide','widget_sdk'],
            ['Notifications & Maintenance','notify_admin'],['Access Control','user_admin'],['Audit Log','audit_log'],['Licensing','license'],
        ],
    ];
}

function nm_copilot_kb($conn, array $context = [], string $username = ''): string {
    $help = nm_copilot_pagehelp();
    $menu = nm_copilot_menu_map();

    // ── navigation map (built from the live menu structure) ──────────────────
    $nav = '';
    foreach ($menu as $group => $items) {
        $nav .= "\n**{$group}**\n";
        foreach ($items as [$label, $key]) {
            $blurb = $help[$key] ?? $label;
            $nav .= "- {$label} — {$blurb}\n";
        }
    }

    // ── who is asking + what they can reach (so we only point them to allowed pages) ──
    $role = $_SESSION['role'] ?? ($context['role'] ?? 'user');
    $allowed = [];
    if ($conn instanceof mysqli && function_exists('checkAccess')) {
        foreach (nm_perm_catalog() as $r) {
            $k = $r[0];
            try { if (checkAccess($conn, $k)) $allowed[] = $r[1]; } catch (\Throwable $e) {}
        }
    }
    $allowedTxt = $allowed ? implode(', ', $allowed) : '(unknown)';
    $page = $context['page'] ?? '';
    $pageLabel = $context['page_label'] ?? '';

    $kb = <<<KB
# NEURU PORTAL — OPERATOR KNOWLEDGE BASE
You are the **NetOps Copilot for NEURU** (Neural Network Monitor) — both a senior network engineer AND a NEURU portal expert. NEURU is a self-hosted, flat-file PHP + MySQL + n8n network-monitoring and automation platform that goes well beyond conventional NMS (SolarWinds-class and past it). Answer ANY question about the network OR about the portal itself: where an option is, how to configure something, what a page does, how a feature works, and step-by-step how-tos. When the question is operational ("why is X slow", "is Y down", "who's using bandwidth"), use your live read-API tools to check real data before answering. When it's a "how do I / where is" question, answer from this knowledge base with an exact click-path.

## HOW TO ANSWER (rules)
- Be concise and concrete. For "where is X / how do I X", give the **exact click-path** (e.g. "Menu ▸ Site Configuration ▸ Config → Global Settings tab → Ping Down Sensitivity").
- Only point the user to pages they can actually reach (their accessible pages are listed below). If a feature needs a permission they lack, say so and suggest asking an admin (Access Control).
- Prefer numbered steps for procedures. Use **bold** for UI labels and `code` for field names/values.
- If something is operational, cite what you checked (put it in the `evidence` array). Don't invent data — if a tool returns nothing, say so.
- Never expose secrets, tokens, passwords, or private keys. If asked, explain where they're configured, not their values.
- If you're unsure where something lives, say so rather than guessing a wrong menu path.

## WHO IS ASKING
- User: **{$username}** · role: **{$role}**
- Current page: **{$pageLabel}** ({$page})
- Pages this user can access: {$allowedTxt}

## WHERE EVERYTHING LIVES (navigation map)
The top bar shows **Home** (Command Deck), **Dashboard**, **Incidents**. The immersive full-screen views live under **Menu ▸ Command Centers**: **NEURU Commander** (the autonomous NOC agent — autopilotv2.php), **Command Center** (the widget map), **Map**, **Geo Wall**, **Traffic Hologram**, **Router Command Center**, **DB Observatory**, **Service Biosphere**. Everything else is under the **Menu** dropdown, grouped (the AI pages — **AI Insights**, AI/GPU Monitor, AI Archaeologist — are under **Menu ▸ AI Tools**; the security-response pages — **Collective Immunity**, **Self-Healing**, **Deception Grid** — are under **Menu ▸ Healing**):
{$nav}

## HOW-TO RECIPES (most common requests)

### Add or configure a node
1. **Menu ▸ Site Configuration ▸ Config** → **Nodes** tab.
2. **Add node directly** (no LibreNMS needed): give it a display name + IP, and choose `monitor_type`:
   - `snmp` → set SNMP community + version (v1/v2c/v3). NEURU polls interfaces/CPU/etc. over SNMP.
   - `ping` → ICMP-only up/down + latency (good for WAN checks like 8.8.8.8, or hosts without SNMP).
3. Per-node extras on the same tab: SNMP credentials, `gateway_node_id` (for topology/blast-radius), `graylog_source` override, geo lat/long (for Geo Wall), and SSH credential assignment.

### Fix false "device down" alarms / tune ping sensitivity
- **Menu ▸ Site Configuration ▸ Config** → **Global Settings** tab → **Ping Down Sensitivity**.
- It's the number of consecutive failed ICMP polls (poller runs every minute) before a ping node is declared DOWN. Default **3** (~3 min). Lower = faster detection but more false alarms; higher = fewer false alarms. Recovery is always instant.

### Create a widget for the Command Center (3 ways — no coding needed)
- **Widget Studio** (Menu ▸ Site Configuration ▸ Widget Studio): a no-code builder. Pick a data source, a look (stat / list / bar / table / 🔔 alarm / 🎵 sonify), map the fields, live-preview, Save. It then appears in the Command Center Widgets menu.
- **Widget Marketplace** (same menu): install ready-made NEURU widgets or community widgets; Preview/Code before installing. You can delete only widgets YOU created; NEURU originals can't be deleted.
- **Import / AI**: paste a `.neuruwidget` JSON (or one an AI wrote for you) → Validate → Install. The **Widget SDK Guide** page has a copy-able AI prompt with all live data sources baked in.
- Widgets are safe: they declare which curated, read-only data sources they `need`; the portal resolves them with YOUR permissions. Widgets never touch the DB, SQL, or secrets.

### Silence alerts during maintenance / manage notifications
- **Menu ▸ Site Configuration ▸ Notifications & Maintenance** (notify_admin.php). Open a maintenance window (site-wide or per-node/source) to suppress alerts; all module alerters (Smokeping, NetFlow, Netstat, etc.) honor it. Configure notification routing here too.

### See services as living organisms (Service Biosphere)
- **Menu ▸ Command Centers ▸ Service Biosphere** (`biosphere.php`). Each service (DNS/HTTP/SQL/SMTP/generic) is a living 3D cell; every visual is a TRUE signal — membrane breathes/swells on real latency, dark "infection" patches on real 4xx/5xx, "sludge" on SQL saturation/slow queries, an icy "freeze" on a DB lock. Click a cell for its dossier (latency sparkline, kind-specific vitals, heaviest queries for SQL, flags, symbiosis). Read-mostly; the LLM never executes.
- **Setup:** open the **🎛 Manage** drawer → **Add / Edit** → name it, pick the kind, and give a target: HTTP takes a URL (optional expect-code / body-match), DNS takes a resolver IP (+ optional test name and a linked Pi-hole for cache-hit), **SQL reuses a Data Core target** (no new credentials), SMTP/generic take host+port. **Test probe** reads it live; **Settings** set poll interval + latency thresholds. The **`cron_biosphere.php`** poller must run every minute (curl→localhost with the X-NetMon-Token) for cells to breathe.
- **Symbiosis:** glowing pathways link dependent services; a dependent whose node has an open incident goes translucent ("hibernating — waiting on its root") instead of alarming — it reuses the same incident correlation as Troubleshooting.
- **Antibodies (AI, P2):** the **Antibodies** tab (and per-cell flags) collect AI findings. **DNS DGA audit** (Manage → Settings → enable) ships unusual high-entropy resolved domains from Pi-hole-linked DNS cells to the n8n `bio-dns-audit` flow; verdicts become flags and a high score **auto-promotes to a fleet-wide Immunity block** (or click 🛡 Block). **SQL Auto-Tune:** a distressed SQL cell raises a flag; **🧠 Analyze** reuses the Data Core `db-advisor` flow, then a whitelisted index/maintenance fix shows **⚡ Auto-Tune** → sends the DDL to **Telegram** for Approve/Deny (same bot as NetAIObot) and applies on ✅.
- **Synthetic persona (P3, AI):** an HTTP cell → **✎ Define journey** (login persona + steps: goto/click/expect/expect_text/fill/wait). A **headless browser in n8n** (`bio-http-synthetic`) plays it as a real user and measures **Visual Completeness Time**. When a step fails, a **`ux_break`** Antibody fires and the cell **splits off a wireframe clone** — UX degradation shown distinct from up/down. Enable **Synthetic journeys** in Settings; the login password is stored encrypted. Setup + n8n contracts: `docs/N8N_BIOSPHERE.md`.

### See who's using bandwidth right now
- **Menu ▸ Monitoring ▸ NetFlow** for full top-talkers/apps/protocols/destinations (Flow Explorer; filter by host).
- Or **Menu ▸ Monitoring ▸ Network Sonar** → "Who's using it" panel: click a talker for an instant who/where/what drill-down (GeoIP, reverse DNS, destinations, apps) with Traceroute / Open-in-NetFlow links. Note Sonar's headline "Mb/s (iface agg)" double-counts hops; the NetFlow number is the real attributed traffic.

### Block a threat everywhere at once
- **Menu ▸ Healing ▸ Collective Immunity**. Add/confirm a threat and **Vaccinate** it — NEURU pushes the block to every Pi-hole (DNS deny) and firewall (SSH) at once. It also auto-detects port-scans and malicious DNS.

### Deceive an attacker (Deception Grid) — divert to a honeypot instead of just blocking
- **Menu ▸ Healing ▸ Deception Grid** (`deception.php`). Active defense: divert one attacker IP into a decoy by reprogramming the border router's firewall — **dst-nat placed first + a first-position ALLOW filter rule WITH logging** so the honeypot actually receives the traffic and every hit is captured for Watch (time-boxed, auto-reverting). **Vendor-universal: MikroTik + Cisco ASA** (others pluggable). Watch them, let the AI judge, then promote to a fleet block. **OFF by default.** Full guide: `docs/DECEPTION_GRID.md`.
- **Setup (once):** (1) **Honeypots** tab → add a **turnkey** image — *Cowrie* (`cowrie/cowrie:latest`, SSH) or *whoami* (`traefik/whoami:latest`, HTTP); pick the Portainer host → **Deploy** (the row shows the live container state, ▶ running vs ⚠ restarting). Never clone a real DB; OpenCanary is not turnkey (crash-loops). (2) **Settings** → set the **Border MikroTik** (the router where NAT is applied — must be one you manage AND that the attacker traffic transits), **TTL** (auto-revert, default 30m), **never-divert allowlist** (your admin IPs + internal CIDRs), then flip the **master switch ON**.
- **Manual:** **Diversions** tab → type the attacker IP (a live badge shows its status) → pick honeypot → **Divert**. **👁 Watch** = live "attacker theater" of what they did inside the decoy. **🧠 Analyze** = the n8n `deception-analyst` flow returns a threat score + verdict (promote/observe/release) + summary. **Promote** = block across all Pi-holes + firewalls. **Revert** = remove the NAT + allow-filter rules (by comment).
- **Autonomous mode (Settings → 🤖):** auto-diverts Immunity-detected port-scan/brute-force IPs (≤3/min), auto-analyzes, and auto-promotes when the AI says "promote" and ≥ N events accumulated. Needs a deployed honeypot + the enabled `deception-analyst` webhook.
- **Border-path scoping (multi-router):** a dst-nat only intercepts traffic through the router it's on. NEURU knows which router logged each scan (`reported_by`), so **auto-divert only acts on threats your border router saw**; manual divert **warns** if an IP was seen on a different (unmanaged) router.
- **Coordination:** one IP = one disposition. Diverting an IP already **blocked** (Immunity/Heal) is refused; if an IP gets blocked while diverted, the divert auto-reverts within a minute (block supersedes divert).
- **Common "why didn't it divert?"** → master switch or auto OFF · no deployed honeypot · IP on the never-divert allowlist · IP is internal and "allow internal" is off · IP already blocked/diverted · the threat was seen only on a non-border router.
- **Shortcut:** you can **Divert an IP threat straight from Collective Immunity** — each IP threat row has a **Divert** button (next to Vaccinate/Dismiss) that sends it to the Deception Grid honeypot, so you don't have to switch pages. Needs the `deception` permission + a deployed honeypot. Immunity also has a **🎭 Diverted** filter tab and shows a "diverted" badge on any IP being diverted; **Self-Healing (heal.php)** shows the same badge on events whose IP is diverted. Note: diverting does NOT change the Immunity status (a divert is not a block) — the threat stays "pending" with a diverted badge until you Promote (→ active/blocked) or it reverts.

### Configure Pi-hole, NetFlow, Smokeping, Syslog, Switches
- All under **Menu ▸ Site Configuration ▸ Config**, each on its own tab. Pi-hole stores an encrypted password and caches its session. NetFlow has a collector + retention. Syslog is NEURU's own server (default log source). Switches tab adds TP-Link Easy Smart switches.

### Set up SSH credentials (for Config Manager, Self-Healing, WireGuard, Immunity)
- **Menu ▸ Site Configuration ▸ Config → Integrations & AI → SSH Credentials**. Add a credential (name / username / password or private key / port), mark one **Default**, and optionally assign per-device. Secrets are AES-256-GCM encrypted at rest and never shown back.

### Connect AI / n8n automations
- **Menu ▸ Site Configuration ▸ Config → Integrations & AI**: set the n8n base URL + API key, generate the inbound token, and register webhooks by slug (e.g. `netops-copilot`, `log-rca`, `self-heal`). See "About this Copilot's AI" below.

### Users, roles, and permissions
- **Menu ▸ Site Configuration ▸ Access Control** (access_admin.php). Layered RBAC: a base role plus per-user allow/deny overrides; deny always wins. It's lockout-proof and every change is in the Audit Log.

### Fix wrong times / timezone
- **Menu ▸ Site Configuration ▸ Config → Global Settings → Display Timezone**. NEURU stores everything in UTC and displays in your chosen timezone (default America/Puerto_Rico).

## WIDGET SDK — DATA SOURCES
Widgets read from a curated broker (permission-checked, read-only). Sources include: active incidents, node status, nodes down, NetFlow (top/apps/protocols/destinations/summary), top interfaces, recent syslog & syslog errors, containers, Smokeping latest, Pi-hole top, ping-by-node, Predictive-Health forecasts, Wear scores, SLA per node, and WireGuard peers. The live, exact list (with fields) is on the **Widget SDK Guide** page.

### Let the AI watch (and optionally fix) a device — with phone approval
1. Open **NEURU Commander** (Menu ▸ Command Centers, brain icon, `autopilotv2.php`) → its devices / autonomy controls.
2. **Add a device**, then pick its autonomy tier: **Observe** (watch only), **Copilot** (propose & ask), or **Autopilot** (auto-run safe fixes). Optional per-device toggles: *medium-risk auto*, *auto-run commands* (high-risk, red), and **📱 Telegram approval**.
3. With **Telegram approval** on, whenever the AI needs an OK it sends the exact command + reason to Telegram with **Approve / Deny** buttons — tap from your phone; approve runs it via the portal, deny keeps manual control. (The bot is the one you set in **Notifications & Maintenance**.)
4. The bot console streams every Observe→Think→Act→Result step; pending approvals also show on the page with Approve/Deny. This is NOT the "Command Center" (that is the drag-and-drop widget map).

## GLOSSARY (NEURU terms)
- **Command Center vs NEURU Commander:** *Command Center* (`command.php`) is the interactive NOC **map with draggable widgets**. *NEURU Commander* (`autopilotv2.php`) is the **autonomous AI agent** that observes/acts on the devices you select. Different pages, different purposes — don't conflate them. (The old *AI Command Center* / NetAIObot `aiopilot.php` is retired — superseded by NEURU Commander.)
- **Incident vs Insight:** an *Insight* (AI Insights page) is a single AI/automation finding; an *Incident* (Incident Command) correlates many signals into one root issue.
- **Blast radius:** when a core device drops, downstream alarms are grouped under one master incident so you see the origin, not 500 alarms.
- **Vaccinate (Immunity):** apply a threat block to every Pi-hole + firewall at once.
- **Divert (Deception):** redirect ONE attacker IP's traffic into a decoy honeypot via a time-boxed dst-nat + allow-filter on the border router (vendor-universal: MikroTik / Cisco ASA) — you observe them instead of (or before) blocking. Auto-reverts on the TTL.
- **Honeypot / decoy (Deception):** a low-interaction container (Cowrie / whoami) the attacker is diverted into; its captured interactions show in the "attacker theater". Never a clone of a real service.
- **Promote (Deception):** escalate a diverted IP to a fleet-wide Collective Immunity block, then revert the decoy — the deception's job is done.
- **Border-path scoping (Deception):** a dst-nat only intercepts traffic transiting the router it's applied on, so NEURU only diverts threats whose logs come from the border router you manage (multi-router safety).
- **Disposition (Deception coordination):** an IP is in exactly one state — clear, diverted, or blocked. A block supersedes a divert; you can't divert an already-blocked IP.
- **iface agg (Sonar):** interface-aggregate Mb/s — sums in+out on every port, so it counts each hop; NetFlow is the real attributed total.
- **Baseline (Stats):** learned mean ±2σ per hour-of-week — "normal for this time", not a static threshold.

## ABOUT THIS COPILOT'S AI (for advanced/meta questions)
This chat is a slide-out widget on every page → it POSTs to the portal proxy `nm_copilot.php` → which relays to the n8n flow registered under slug **`netops-copilot`** (the inbound token is added server-side so the flow can call back). The flow's LLM has read-only tools that hit NEURU's token-guarded read API (nodes, topology, metrics, ports, ping, logs, insights, baselines) and replies with `{answer, evidence[], diagram?}`. To change the Copilot's behavior, edit that n8n flow; to register/enable it, use Config → Integrations & AI.
KB;

    return $kb;
}

} // function_exists guard
