<?php
// ─────────────────────────────────────────────────────────────────────────────
// NEURU — shared media / image upload helper (equipment photos, user avatars, …).
// First upload flow in the app, so it's deliberately strict:
//  · real-image validation via getimagesize() (not just extension/MIME header)
//  · randomized filenames (no user-controlled names on disk)
//  · a hardened .htaccess per upload dir that NEUTRALISES PHP execution while
//    still allowing the image to be served as a static <img src>.
// Storage lives under uploads/ in the app root — a persisted bind-mount, so files
// survive container recreate (same pattern as .nm_secret.key / logs/). www-data writes.
// ─────────────────────────────────────────────────────────────────────────────

if (!function_exists('nm_media_root')) {

    // Absolute path to the uploads root (app-root/uploads). Created on demand.
    function nm_media_root(): string { return __DIR__ . '/uploads'; }

    // Web-relative base used in <img src="…"> (pages live in the app root too).
    function nm_media_web_base(): string { return 'uploads'; }

    // Allowed image types → canonical extension.
    function nm_media_types(): array {
        return [IMAGETYPE_JPEG => 'jpg', IMAGETYPE_PNG => 'png', IMAGETYPE_GIF => 'gif', IMAGETYPE_WEBP => 'webp'];
    }

    // Ensure uploads/<sub> exists and is locked down against script execution.
    // Best-effort: returns the absolute dir path, or null if it can't be created.
    function nm_media_ensure_dir(string $sub): ?string {
        $root = nm_media_root();
        $dir  = $root . '/' . trim($sub, '/');
        try {
            if (!is_dir($root)) { @mkdir($root, 0755, true); }
            if (!is_dir($dir))  { @mkdir($dir, 0755, true); }
            if (!is_dir($dir))  return null;
            // Harden once: disable PHP handlers so a disguised .php upload can't run,
            // but leave static image serving intact.
            $ht = $root . '/.htaccess';
            if (!is_file($ht)) {
                @file_put_contents($ht,
                    "# Auto-generated by NEURU — serve images, never execute code here.\n" .
                    "php_flag engine off\n" .
                    "Options -ExecCGI -Indexes\n" .
                    "RemoveHandler .php .phtml .php3 .php4 .php5 .php7 .phar\n" .
                    "RemoveType .php .phtml .php3 .php4 .php5 .php7 .phar\n" .
                    "<FilesMatch \"\\.(php[0-9]?|phtml|phar|cgi|pl|py|sh)$\">\n" .
                    "  Require all denied\n" .
                    "</FilesMatch>\n"
                );
                @chmod($ht, 0644);
            }
            return $dir;
        } catch (\Throwable $e) { return null; }
    }

    // Validate + store one uploaded image. $file is an entry from $_FILES.
    // Returns ['ok'=>true,'path'=>'uploads/<sub>/<name>'] or ['ok'=>false,'error'=>…].
    // $prefix labels the file on disk (e.g. "node7", "avatar12"); $maxBytes caps size.
    function nm_media_store_image(array $file, string $sub, string $prefix = 'img', int $maxBytes = 8388608): array {
        if (!isset($file['error']) || is_array($file['error']))       return ['ok'=>false,'error'=>'no file'];
        if ($file['error'] === UPLOAD_ERR_NO_FILE)                    return ['ok'=>false,'error'=>'empty'];
        if ($file['error'] !== UPLOAD_ERR_OK)                         return ['ok'=>false,'error'=>'upload error '.$file['error']];
        if (($file['size'] ?? 0) <= 0 || $file['size'] > $maxBytes)   return ['ok'=>false,'error'=>'file too large (max '.round($maxBytes/1048576).' MB)'];
        if (!is_uploaded_file($file['tmp_name'] ?? ''))               return ['ok'=>false,'error'=>'invalid upload'];

        $info = @getimagesize($file['tmp_name']);           // real-image check (rejects disguised scripts)
        $types = nm_media_types();
        if (!$info || !isset($types[$info[2]]))                       return ['ok'=>false,'error'=>'not a supported image (JPG/PNG/GIF/WebP)'];
        $ext = $types[$info[2]];

        $dir = nm_media_ensure_dir($sub);
        if (!$dir)                                                    return ['ok'=>false,'error'=>'upload dir not writable'];

        $safePrefix = preg_replace('/[^a-z0-9_]/i', '', $prefix) ?: 'img';
        try { $rand = bin2hex(random_bytes(8)); } catch (\Throwable $e) { $rand = substr(md5(uniqid('', true)), 0, 16); }
        $name = $safePrefix . '_' . $rand . '.' . $ext;
        $dest = $dir . '/' . $name;

        if (!@move_uploaded_file($file['tmp_name'], $dest))          return ['ok'=>false,'error'=>'could not save file'];
        @chmod($dest, 0644);
        return ['ok'=>true, 'path' => nm_media_web_base() . '/' . trim($sub, '/') . '/' . $name];
    }

    // Delete a previously-stored relative path (best-effort; guards against escaping uploads/).
    function nm_media_delete(?string $relPath): void {
        if (!$relPath) return;
        $rel = ltrim(str_replace('\\', '/', $relPath), '/');
        if (strpos($rel, '..') !== false) return;
        if (strpos($rel, nm_media_web_base() . '/') !== 0) return;   // only touch our own uploads/
        $abs = __DIR__ . '/' . $rel;
        if (is_file($abs)) @unlink($abs);
    }
}
