<?php
// ─────────────────────────────────────────────────────────────────────────────
// NEURU — WireGuard interconnect (client side of the hosted "NEURU AI Flows").
//
// Most NEURU installs sit behind NAT, so the hosted n8n can't reach them to deliver
// flow callbacks. Toggling this ON asks the NEURU Portal to provision a WireGuard
// peer (the Portal drives wg-easy on the n8n VPS); the Portal returns a ready wg0.conf
// + the assigned tunnel IP. We drop the conf in wg/wg0.conf — a small WireGuard SIDECAR
// container (sharing this web container's network namespace) sees it and brings the
// tunnel UP (outbound, NAT-friendly). We then point flow callbacks at the tunnel IP
// (ai_public_base) so n8n reaches this NEURU at http://<tunnel-ip>. OFF tears it down.
//
// The customer pastes NOTHING — one toggle. Keys + IP are generated by the Portal/wg-easy.
// ─────────────────────────────────────────────────────────────────────────────
require_once __DIR__ . '/nm_license.php';   // nm_lic_api_base / nm_lic_row / nm_lic_fingerprint

if (!function_exists('nm_wgconn_dir')) {

    function nm_wgconn_dir(): string {
        $d = __DIR__ . '/wg';
        if (!is_dir($d)) @mkdir($d, 0775, true);
        return $d;
    }

    function _wg_set($conn, string $k, string $v): void {
        $st = $conn->prepare("INSERT INTO nm_settings(setting_key,setting_val) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_val=?");
        $st->bind_param('sss', $k, $v, $v); $st->execute(); $st->close();
    }
    function _wg_get($conn, string $k, string $d = ''): string {
        $r = $conn->query("SELECT setting_val FROM nm_settings WHERE setting_key='" . $conn->real_escape_string($k) . "' LIMIT 1");
        return ($r && $x = $r->fetch_row()) ? (string)$x[0] : $d;
    }

    function nm_wgconn_state($conn): array {
        // link_up = the WireGuard interface is ACTUALLY up in our (shared) network namespace.
        // The neuru-wg sidecar (network_mode: service:web) brings wg0 up in the web container's
        // netns, so /sys/class/net/wg0 becomes visible here. This is the honest "really connected"
        // signal — distinct from wg_status (the stored intent). A box WITHOUT the sidecar (e.g. a
        // bespoke dev container) writes the conf + flips wg_status='on' but wg0 never appears →
        // link_up=false → the UI can tell the truth instead of falsely reporting "Connected".
        return [
            'status'       => _wg_get($conn, 'wg_status', 'off'),
            'ip'           => _wg_get($conn, 'wg_ip', ''),
            'last_err'     => _wg_get($conn, 'wg_last_err', ''),
            'updated_at'   => _wg_get($conn, 'wg_updated_at', ''),
            'conf_present' => is_file(nm_wgconn_dir() . '/wg0.conf'),
            'writable'     => is_writable(nm_wgconn_dir()),
            'link_up'      => is_dir('/sys/class/net/wg0'),
        ];
    }

    // POST JSON to the Portal's /v1/wg/* → ['ok'=>bool, 'data'=>?, 'err'=>?]
    function _wg_portal($conn, string $path, array $body): array {
        $base = function_exists('nm_lic_api_base') ? nm_lic_api_base($conn) : '';
        if ($base === '') return ['ok' => false, 'err' => 'Portal API URL not configured'];
        $ch = curl_init(rtrim($base, '/') . $path);
        curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_POST => true,
            CURLOPT_HTTPHEADER => ['Content-Type: application/json'], CURLOPT_POSTFIELDS => json_encode($body),
            CURLOPT_CONNECTTIMEOUT => 6, CURLOPT_TIMEOUT => 20,
            CURLOPT_NOSIGNAL => true,          // CRITICAL in threaded Apache: makes the timeouts actually
            CURLOPT_CONNECTTIMEOUT_MS => 6000, // fire (SIGALRM-based timeouts don't work under threads →
            CURLOPT_TIMEOUT_MS => 20000,       // the request would hang forever instead of erroring out).
            CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,  // skip IPv6 — a broken v6 route in a container makes
                                                     // libcurl's connect hang (shell curl falls back, PHP doesn't).
            CURLOPT_SSL_VERIFYPEER => false, CURLOPT_SSL_VERIFYHOST => false]);
        $res = curl_exec($ch); $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE); $err = curl_error($ch); curl_close($ch);
        if ($res === false || $code === 0) return ['ok' => false, 'err' => $err ?: 'connection failed'];
        $j = json_decode($res, true);
        if ($code < 200 || $code >= 300) return ['ok' => false, 'err' => ($j['error'] ?? ('HTTP ' . $code))];
        return ['ok' => true, 'data' => is_array($j) ? $j : []];
    }

    // Turn the tunnel ON: enroll with the Portal, write the conf, point callbacks at the tunnel IP.
    function nm_wgconn_enroll($conn): array {
        $row = function_exists('nm_lic_row') ? nm_lic_row($conn) : null;
        $lic = is_array($row) ? (string)($row['license_key'] ?? '') : '';
        $fp  = function_exists('nm_lic_fingerprint') ? nm_lic_fingerprint() : '';
        $connKey = _wg_get($conn, 'ai_conn_key', '');
        $r = _wg_portal($conn, '/v1/wg/enroll', ['license_key' => $lic, 'fingerprint' => $fp, 'conn_key' => $connKey]);
        if (!$r['ok']) { _wg_set($conn, 'wg_last_err', (string)$r['err']); return ['ok' => false, 'error' => $r['err']]; }
        $conf = (string)($r['data']['wg_conf'] ?? '');
        $ip   = (string)($r['data']['wg_ip'] ?? '');
        if ($conf === '' || $ip === '') { _wg_set($conn, 'wg_last_err', 'portal returned no config'); return ['ok' => false, 'error' => 'The Portal returned no tunnel config.']; }
        $f = nm_wgconn_dir() . '/wg0.conf';
        if (@file_put_contents($f, $conf) === false) {
            _wg_set($conn, 'wg_last_err', 'cannot write wg0.conf');
            return ['ok' => false, 'error' => 'Cannot write wg/wg0.conf — the wg/ folder must be writable by www-data.'];
        }
        @chmod($f, 0600);
        _wg_set($conn, 'wg_ip', $ip);
        _wg_set($conn, 'wg_status', 'on');
        _wg_set($conn, 'wg_enabled', '1');
        _wg_set($conn, 'ai_public_base', 'http://' . $ip);   // flows now call back via the tunnel IP
        _wg_set($conn, 'wg_last_err', '');
        _wg_set($conn, 'wg_updated_at', date('Y-m-d H:i:s'));
        return ['ok' => true, 'ip' => $ip];
    }

    // Turn the tunnel OFF: tell the Portal, remove the conf (sidecar tears it down), clear state.
    function nm_wgconn_disable($conn): array {
        $row = function_exists('nm_lic_row') ? nm_lic_row($conn) : null;
        $lic = is_array($row) ? (string)($row['license_key'] ?? '') : '';
        $connKey = _wg_get($conn, 'ai_conn_key', '');
        // best-effort — never let a Portal error block the local teardown
        _wg_portal($conn, '/v1/wg/disable', ['license_key' => $lic, 'conn_key' => $connKey]);
        $f = nm_wgconn_dir() . '/wg0.conf'; if (is_file($f)) @unlink($f);
        $ip = _wg_get($conn, 'wg_ip', '');
        if ($ip !== '' && _wg_get($conn, 'ai_public_base', '') === 'http://' . $ip) _wg_set($conn, 'ai_public_base', '');
        _wg_set($conn, 'wg_status', 'off');
        _wg_set($conn, 'wg_enabled', '0');
        _wg_set($conn, 'wg_ip', '');
        _wg_set($conn, 'wg_updated_at', date('Y-m-d H:i:s'));
        return ['ok' => true];
    }
}
